kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  # Any name can be used here
  name: dev-repo
  namespace: fleet-local
spec:
  repo: https://github.com/raulcabello/fleet-examples
  branch: dev
  targetNamespace: devgitrepo
  paths:
  - simple
  targets:
    - name: dev
      clusterSelector:
        env: test
